"""add workspace visibility

Revision ID: 3362d890022c
Revises: 98fa72294e85
Create Date: 2026-08-20 20:52:34.528102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3362d890022c'
down_revision: Union[str, Sequence[str], None] = '98fa72294e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('visibility', sa.String(), server_default='private', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'visibility')
    # ### end Alembic commands ###
